version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:13.7.0-ce.0
    user: root
    container_name: gitlab_container
    ports:
      - "800:80"
      - "4433:443"
      - "222:22"
    # volumes:
    #   - '$HOME/docker-share/gitlab/config:/etc/gitlab'
    #   - '$HOME/docker-share/gitlab/logs:/var/log/gitlab'
    #   - '$HOME/docker-share/gitlab/data:/var/opt/gitlab'
    # volumes:
    #   - 'D:\Develop\Docker\docker-share\gitlab\config:/etc/gitlab'
    #   - 'D:\Develop\Docker\docker-share\gitlab\logs:/var/log/gitlab'
    #   - 'D:\Develop\Docker\docker-share\gitlab\data:/var/opt/gitlab'
    # volumes:
    #   - "/docker-share/gitlab/cfg:/etc/gitlab"
    #   - "/docker-share/gitlab/logs:/var/log/gitlab"
    #   - "/docker-share/gitlab/data:/var/opt/gitlab"
    # restart: always
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   user: root
  #   container_name: jenkins_container
  #   ports:
  #     - "8081:8080"
  #   # volumes:
  #   #   - "/var/run/docker.sock:/var/run/docker.sock"
  #   #   - "/data/jenkins:/var/jenkins_home"
  #   #   - "/usr/bin/docker:/usr/bin/docker"
  #   # restart: always